version: 0.1
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaprojectawsaa -Dsonar.organization=javaprojectawsa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b2f3517026d0e39110a8fe7e17e9ee1f97023d89 
